// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	
	int n = Integer.parseInt(args[0]);	
	double aboveHalfCount = 0.0; //>0.5
	double belowHalfCount = 0.0; //<=0.5
	double ratio = 1.0; // for the edge case, 

	for(int i=0 ; i<n; i++){
	
		if(Math.random() > 0.5)
			aboveHalfCount++;
		else
			belowHalfCount++;
	}
	if(aboveHalfCount > belowHalfCount)
	{
		ratio = belowHalfCount/aboveHalfCount;
		if(ratio != 0)
		{
		System.out.println("> 0.5: " + (int)aboveHalfCount);
		System.out.println("<= 0.5: " + (int)belowHalfCount);
		System.out.println("Ratio :" + ratio);
		}
		else
		{
		System.out.println("> 0.5: " + (int)aboveHalfCount);
		System.out.println("<= 0.5: " + (int)belowHalfCount);
		}
	}
	else
	{
		ratio = aboveHalfCount/belowHalfCount;
		if(ratio != 0)
		{
		System.out.println("> 0.5: " + (int)aboveHalfCount);
		System.out.println("<= 0.5: " + (int)belowHalfCount);
		System.out.println("Ratio: " + (int)ratio);
		}
		else
		{
		System.out.println("> 0.5: " + (int)aboveHalfCount);
		System.out.println("<= 0.5: " + (int)belowHalfCount);
		}
	}
}
}
	


